### ISSUE TITLE
How does this work in .NET 6?

### ISSUE THREAD

**Issue by HarlanAtWork** [HangfireIO/Hangfire.Documentation#122]
In .NET 6, without global.asax, what do we have to do to make Hangfire start right up? And how does the part about making it stop on application end work?

**Comment by odinserj** [comment]
Please see this guide to learn how to configure Hangfire to work with ASP.NET Core – https://docs.hangfire.io/en/latest/getting-started/aspnet-core-applications.html

**Comment by HarlanAtWork** [comment]
I have Hangfire already working in my .NET 6 app. My question specifically was about this article, "Making ASP.NET application always running", which gave me the impression that there are additional step _beyond_ the basic installation, to ensure that the scheduler starts as soon as the website starts. Or were extra steps required only under .NET Framework? Is autostart of the scheduler automatic under .NET Core?

**Comment by odinserj** [comment]
Yes, it's mainly for .NET Framework. Did you check this section – https://docs.hangfire.io/en/latest/deployment-to-production/making-aspnet-app-always-running.html#making-asp-net-core-application-always-running-on-iis ?

**Comment by kdubious** [comment]
@odinserj , or anyone else... the steps in the link to the doc section above makes sense to me. However, I can't tell if I ALSO need to make the classes from earlier in that document or not (Creating classes). Do I? Or does ASPNET CORE handle that plumbing?

**Comment by kdubious** [comment]
@HarlanAtWork Have you worked out the details?

**Comment by HarlanAtWork** [comment]
It's all working now as required in our .NET Core 6 environment, without any additional work. It turned out the only thing holding us up was keeping the site _alive_, which was resolved by scheduling regular keep-alive pings. Thanks.
