### ISSUE TITLE
Upgrading to HangFire 1.8 documentation references old DefaultInstall.sql and Install.sql

### ISSUE THREAD

**Issue by aescg1220** [HangfireIO/Hangfire.Documentation#123]
In the [manual migration](https://github.com/HangfireIO/Hangfire.Documentation/blob/master/upgrade-guides/upgrading-to-hangfire-1.8.rst#manual-migration), both of the DefaultInstall.sql and Install.sql links appear to be referencing 1.7 files.  Please update these to reference the 1.8 files.

**Comment by odinserj** [comment]
Thanks for the hint, @aescg1220! Fixed the issue.
