### ISSUE TITLE
Is there a way to pass an existing IDbConnection (with IDbTransaction) to the library, so that commands would go through the given connection?

### ISSUE THREAD

**Issue by hidegh** [HangfireIO/Hangfire.Documentation#5]
Classic issue is when using NHibernate is when transaction get's distributed. Since this kind of solution mostly works in a web environment, in a single DB model, re-using NHibernate's ADO-DB connection would save us from **distributed transactions** (and it's side effects when using then with NHibernate).

**This request relates to publishing only**: since you want to execute some code then in the end publish a task - and these 2 must be done in a transaction...

The job-servers does not need this feature.

**Comment by oguzhaneren** [comment]
Wow it works with nhibernate transaction without msdtc?
Thanks,

**Comment by odinserj** [comment]
Since there are no nested connections, it should work, at least with SQL Server &gt; 2008 as per MSDN docs.

**Comment by hidegh** [comment]
@odinserj 

> Since there are no nested connections, it should work, at least with SQL Server > 2008 as per MSDN docs.

If the connection is not held open by NHibernate, it could work...

So I would consider something like this:
IDBConnection = session.Connection;
var storage = new SqlServerStorage(connection);
var client = new BackgroundJobClient(storage);

According source code, Hangfire is able to open and then close an IDbConnection. But haven't found code that would handle a scenario, where the IDbConnection passed to the SqlServerStorage is already opened.

**The question is:** is it possible to use and pass an opened IDbConnection for the SqlServerStorage, publish (persist) message - and after it rely that the IDbConnection in the same state as it was originally...(is not closed by hangfire)?

**Comment by israellot** [comment]
Any way to pass an existing connection AND also specify the schema name?

**Comment by hidegh** [comment]
@israellot
var storage = new SqlServerStorage(connection); schema name can be passed via SQL command.
